btc/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

from accounts.forms import SignInForm, PswdResetForm, SetPswdForm
from accounts import views as accounts_views
from core import views as core_views

urlpatterns = [
    url(r'^$', accounts_views.HomePageView.as_view(), name='home'),
]

urlpatterns = urlpatterns + [
    url(r'^signup$', accounts_views.signup, name='signup'),
    url(r'^signin$', auth_views.login,
      {
        'template_name': 'accounts/signin.html',
        'authentication_form': SignInForm
      }, name='signin'),
    url(r'^signout$', auth_views.logout, {'next_page': '/'}, name='signout'),
    url(r'^password_reset$', auth_views.password_reset,
      {
        'template_name': 'accounts/password_reset_form.html',
        'password_reset_form': PswdResetForm,
        'email_template_name': 'accounts/password_reset_email.html'
      }, name='password_reset'),
    url(r'^password_reset/done$', auth_views.password_reset_done,
      {
        'template_name': 'accounts/password_reset_done.html'
      }, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})$', auth_views.password_reset_confirm,
      {
        'template_name': 'accounts/password_reset_confirm.html',
        'set_password_form': SetPswdForm
      }, name='password_reset_confirm'),
    url(r'^reset/done$', auth_views.password_reset_complete,
      {
        'template_name': 'accounts/password_reset_complete.html'
      }, name='password_reset_complete'),
    url(r'^plans$', core_views.PlanListView.as_view(), name='plans'),
    url(r'^invest/(?P<plan_name>\w+)$', core_views.InvestView.as_view(), name='invest'),
]

urlpatterns = urlpatterns + [
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Plan(models.Model):
    name = models.CharField(max_length=25)
    deposit = models.DecimalField(max_digits=4, decimal_places=2)
    period = models.IntegerField()
    percentage_return = models.IntegerField()

    def __str__(self):
        return '%s - %s BTC' % (self.name, str(self.deposit))

class Investment(models.Model):
    user = models.ForeignKey(User)
    plan = models.ForeignKey(Plan)
    date_created = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return '%s %s' % (self.user.get_full_name(), self.plan.name)

class Return(models.Model):
    investment = models.ForeignKey(Investment)
    amount = models.DecimalField(max_digits=5, decimal_places=2)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return '%s %s' % (self.investment.user.get_full_name(), str(self.amount))

core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from .models import Investment, Plan

class InvestmentForm(forms.ModelForm):
    plan = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': True}))

    class Meta:
        model = Investment
        exclude = ['plan', 'time_created']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        self.plan = kwargs.pop('plan')
        super(InvestmentForm, self).__init__(*args, **kwargs)

        self.label_suffix = ''

        self.fields['user'].initial = self.user
        self.fields['plan'].initial = str(self.plan.deposit) + ' BTC'
        self.fields['plan'].label = _('Deposit')

        self.fields['user'].widget = forms.HiddenInput()

    def save(self, commit=True):
        deposit = self.cleaned_data['plan'].split(' ')[0]
        plan = Plan.objects.get(deposit=deposit)
        self.instance.plan = plan

        return super(InvestmentForm, self).save(commit)

core/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import FormView

from .models import Investment, Plan
from .forms import InvestmentForm

class PlanListView(ListView):
    model = Plan
    context_object_name = 'plans'

class InvestView(FormView):
    form_class = InvestmentForm
    template_name = 'core/invest.html'

    def plan(self):
        return self.plan

    def get_form_kwargs(self):
        self.plan_name = self.kwargs['plan_name']
        self.plan = Plan.objects.get(name=self.plan_name)

        kwargs = super(InvestView, self).get_form_kwargs()
        kwargs['plan'] = self.plan
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return redirect(reverse('home'))

core/templates/core/invest.html
{% extends 'core/plan_list.html' %}

{% load i18n static %}

{% block content %}
<section class="section">
  <div class="section-title">
    <div class="container">
      <h2 class="title">{% trans view.plan.name %} {% trans "plan" %}</h2>
    </div>
  </div>

  <div class="container">
    <form method="post">

      {% csrf_token %}

      {{ form.user }}

      <div class="form-group">
        {{ form.plan.label_tag }}
        {{ form.plan }}
      </div>

      <input type="submit" class="btn btn-special no-icon" value="{% trans 'Submit' %}">
    </form>
  </div>
</div>
{% endblock %}

core/templates/core/invest_success.html
{% extends 'core/investment_list.html' %}

{% load i18n static %}

{% block content %}
<section class="section">
  <div class="section-title">
    <div class="container">
      <h2 class="title">{% trans "SUCCESS" %}</h2>
      <p class="sub-title">{% trans "Congratulations!" %}</p>
    </div>
  </div>

  <div class="container">
    <div class="row">
      {{ investment }}
    </div>
  </div>
</section>
{% endblock %}

core/templates/core/investment_list.html
{% extends 'core/plan_list.html' %}

{% load i18n static %}

{% block pagetitle %}My Investments{% endblock %}

{% block content %}
<section class="section">
  <div class="section-title">
    <div class="container">
      <h2 class="title">{% trans "My Investments" %}</h2>
    </div>
  </div>

  <div class="container">
    <div class="row">

    </div>
  </div>
</section>
{% endblock %}

core/templates/core/plan_list.html
{% extends 'base.html' %}

{% load i18n static %}

{% block pagetitle %}Investment Plans{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/extra.css' %}">
<link rel="stylesheet" href="{% static 'css/plans.css' %}">
{% endblock %}

{% block header %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#btc-navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <div class="collapse navbar-collapse" id="btc-navbar-collapse">
      <!-- Collect the nav links, forms, and other content for toggling -->
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'plans' %}">{% trans "Investment Plans" %} <span class="sr-only">(current)</span></a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.get_full_name }}<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'home' %}">{% trans "My Investments" %}</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'signout' %}">{% trans "Sign Out" %}</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% endblock %}

{% block app %}
<section class="section"></section>
{% block content %}
<section class="section">
  <div class="section-title">
    <div class="container">
      <h2 class="title">{% trans "Our Investment Plans" %}</h2>
      <p class="sub-title">{% trans "Choose the plan that's best for you!" %}</p>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="block">
        {% for plan in plans %}
          <div class="col-md-6">
            <ul class="pricing {% ifequal plan.name 'starter' %}p-green{% endifequal %} {% ifequal plan.name 'classic' %}p-blue{% endifequal %} {% ifequal plan.name 'deluxe' %}p-yel{% endifequal %} {% ifequal plan.name 'vip' %}p-red{% endifequal %}">
              <li>
                <big {% ifequal plan.name 'vip' %}style="text-transform: uppercase"{% endifequal %}>{{ plan.name }}</big>
              </li>
              <li>Period - <strong>{{ plan.period }}</strong></li>
              <li>{% trans "Total Returns - " %}<strong>{{ plan.percentage_return }}%</strong></li>
              <li>
                <h3><i class="fa fa-btc"></i>{{ plan.deposit }}</h3>
                <span>{% trans "deposit" %}</span>
              </li>
              <li>
                <a href="{% url 'invest' plan_name=plan.name %}" class="button">{% trans "Invest Now" %}</a>
              </li>
            </ul>
          </div>
        {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}
{% endblock %}

{% block extra_js %}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
{% endblock %}